apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-external-bucket
provisioner: rook-ceph-external.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: external-store
  objectStoreNamespace: rook-ceph-external